project:
  type: website
  output-dir: docs

website:
  title: "Rafael Pineda"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - research.qmd
      - teaching.qmd
  announcement: 
    content: "**New** - this is an announcement" 
    position: below-navbar 

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    page-layout: full



